name: 'Get PyPI Latest Version'
description: 'Get the latest version of a package on PyPI and output it'
inputs:
  package:  # id of input
    description: 'Which package to get the version of'
    required: true
outputs:
  version: # id of output
    description: 'The latest version of the requested PyPI package'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
